language: python
services:
    - postgresql
addons:
  postgresql: "9.4"
python:
  - "3.4"
env:
    global:
        - DATABASE_URL=postgres://postgres@localhost/rankme
install:
    - pip install -r requirements/test.txt --use-mirrors
script:
    - ./runtests.sh
before_script:
    - psql -c 'create database rankme;' -U postgres
