# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 16:42
from __future__ import unicode_literals

from django.db import migrations


def twitter_avatars_to_https(apps, schema_editor):
    Profile = apps.get_model('user', 'UserProfile')

    for profile in Profile.objects.all():
        profile.avatar = profile.avatar.replace('http:', 'https:')
        profile.save()


def twitter_avatars_to_http(apps, schema_editor):
    Profile = apps.get_model('user', 'UserProfile')

    for profile in Profile.objects.all():
        profile.avatar = profile.avatar.replace('https:', 'http:')
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20160318_1834'),
    ]

    operations = [
        migrations.RunPython(twitter_avatars_to_https, twitter_avatars_to_http),
    ]
