# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20160318_1643'),
        ('game', '0009_auto_20160317_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='loser_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_lost', to='user.User'),
        ),
        migrations.AddField(
            model_name='game',
            name='winner_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_won', to='user.User'),
        ),
        migrations.AddField(
            model_name='historicalscore',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historical_scores', to='user.User'),
        ),
        migrations.AddField(
            model_name='score',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='user.User'),
        ),
    ]
