# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20160318_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='users',
        ),
        migrations.RenameField(
            model_name='historicalscore',
            old_name='user',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='user',
            new_name='player',
        ),
        migrations.AlterField(
            model_name='competition',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_competitions', to='user.User'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='competitions', to='user.User'),
        ),
        migrations.AlterUniqueTogether(
            name='historicalscore',
            unique_together=set([('player', 'game', 'competition')]),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=set([('competition', 'player')]),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
