# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 17:34
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('game', '0013_auto_20160318_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='competition',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_competitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='competition',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='competitions', to='game.Player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='loser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_lost', to='game.Player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_won', to='game.Player'),
        ),
        migrations.AlterField(
            model_name='historicalscore',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_scores', to='game.Player'),
        ),
        migrations.AlterField(
            model_name='historicalscore',
            name='score',
            field=models.FloatField(verbose_name='Current player score'),
        ),
        migrations.AlterField(
            model_name='historicalscore',
            name='stdev',
            field=models.FloatField(default=8.333, verbose_name='Current player standard deviation'),
        ),
        migrations.AlterField(
            model_name='score',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='game.Player'),
        ),
    ]
