# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 19:40
from __future__ import unicode_literals

from django.db import migrations


def migrate_game_competition(apps, schema_editor):
    Game = apps.get_model('game', 'Game')

    for game in Game.objects.all():
        game.competition = game.competitions.first()
        game.save()


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_game_competition'),
    ]

    operations = [
        migrations.RunPython(migrate_game_competition),
    ]
