# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_auto_20160318_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='games',
        ),
        migrations.AlterField(
            model_name='game',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='game.Competition'),
        ),
    ]
