# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_auto_20160318_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalscore',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_scores', to='game.Competition'),
        ),
    ]
