# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 21:00
from __future__ import unicode_literals
import json

from django.db import migrations


def migrate_hstore_to_json(apps, schema_editor):
    Event = apps.get_model('timeline', 'Event')

    for event in Event.objects.all():
        details_json = {}
        for key, value in event.details.items():
            details_json[key] = value

            if value is not None:
                try:
                    details_json[key] = json.loads(value)
                except ValueError:
                    pass

        event.details_json = details_json
        event.save()


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0004_auto_20160318_2200'),
    ]

    operations = [
        migrations.RunPython(migrate_hstore_to_json),
    ]
