# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 21:04
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0005_auto_20160318_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='details',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='details_json',
            new_name='details',
        ),
    ]
