# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20141209_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='teams',
            field=models.ManyToManyField(related_name='competitions', through='game.Score', to='game.Team'),
        ),
        migrations.AlterField(
            model_name='historicalscore',
            name='score',
            field=models.FloatField(verbose_name='Current team score'),
        ),
        migrations.AlterField(
            model_name='historicalscore',
            name='stdev',
            field=models.FloatField(default=8.333, verbose_name='Current team standard deviation'),
        ),
        migrations.AlterField(
            model_name='score',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='game.Competition'),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.FloatField(default=25, verbose_name='skills'),
        ),
        migrations.AlterField(
            model_name='score',
            name='stdev',
            field=models.FloatField(default=8.333, verbose_name='standard deviation'),
        ),
    ]
