# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 09:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def migrate_game_competition(apps, schema_editor):
    Game = apps.get_model('game', 'Game')

    for game in Game.objects.all():
        game.competition = game.competitions.first()
        game.save()


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20160319_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='teams',
        ),
        migrations.RemoveField(
            model_name='game',
            name='loser',
        ),
        migrations.RemoveField(
            model_name='game',
            name='winner',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='loser_user',
            new_name='loser',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='winner_user',
            new_name='winner',
        ),
        migrations.AlterField(
            model_name='game',
            name='loser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_lost', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_won', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalscore',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='score',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='historicalscore',
            unique_together=set([('player', 'game', 'competition')]),
        ),
        migrations.RemoveField(
            model_name='historicalscore',
            name='team',
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=set([('competition', 'player')]),
        ),
        migrations.RemoveField(
            model_name='score',
            name='team',
        ),
        migrations.RemoveField(
            model_name='team',
            name='users',
        ),
        migrations.AlterField(
            model_name='competition',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='competitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.AddField(
            model_name='game',
            name='competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='game.Competition'),
        ),
        migrations.RunPython(migrate_game_competition),
        migrations.RemoveField(
            model_name='competition',
            name='games',
        ),
        migrations.AlterField(
            model_name='game',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='game.Competition'),
        ),
        migrations.AlterUniqueTogether(
            name='historicalscore',
            unique_together=set([('player', 'game')]),
        ),
        migrations.RemoveField(
            model_name='historicalscore',
            name='competition',
        ),
    ]
