# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20160319_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalscore',
            name='score',
            field=models.FloatField(verbose_name='Current player score'),
        ),
        migrations.AlterField(
            model_name='historicalscore',
            name='stdev',
            field=models.FloatField(default=8.333, verbose_name='Current player standard deviation'),
        ),
    ]
