# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20141010_1712'),
        ('game', '0013_auto_20160405_1002'),
    ]

    operations = [
    ]
