# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 08:21
from __future__ import unicode_literals

from django.db import migrations

def create_sports_and_assign(apps, schema_editor):
    Sport = apps.get_model('game', 'Sport')
    Competition = apps.get_model('game', 'Competition')

    table_tennis = Sport.objects.create(slug='table-tennis', name='Table Tennis')
    darts = Sport.objects.create(slug='darts', name='Darts')
    table_football = Sport.objects.create(slug='table-football', name='Table Football')
    video_game = Sport.objects.create(slug='video-game', name='Video Game')

    sport_competitions = {
        table_tennis: set([
            'la-cup-du-22-mai',
            'liip-lausanne',
            'ls-table-tennis-2015',
            'antistatique',
            'liip-fribourg',
            'ls-table-tennis-2016',
            'mini-ping-pong',
            'thinkspace1',
            'training-germain-sylvain'
        ]),
        darts: set([
            'fribourg-dart-2015',
            'bundebit-darts-competition',
            'fribourg-301-2016',
            'fribourg-cricket-2016',
            'fribourg-dart-competition'
        ]),
        table_football: set([
            'liip-zh-toeggeli-club'
        ]),
        video_game: set([
            'cs',
            'ls-mortal-kombat-x'
        ])
    }

    for sport, competitions in sport_competitions.items():
        Competition.objects.filter(slug__in=competitions).update(sport=sport)

def unassign_competition_sport(apps, schema_editor):
    Sport = apps.get_model('game', 'Sport')
    Competition = apps.get_model('game', 'Competition')

    Sport.objects.all().delete()
    Competition.objects.all().update(sport=None)

class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_auto_20160420_1020'),
    ]

    operations = [
        migrations.RunPython(create_sports_and_assign, unassign_competition_sport),
    ]
