# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_assign_default_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='game.Sport'),
        ),
    ]
