# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_auto_20160420_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='icon',
            field=models.TextField(blank=True),
        ),
    ]
